SET datestyle = "ISO, MDY";
COPY parameters.currency_purchase FROM 'C:\csv\CurrencyPurchaseParameters.csv' WITH (FORMAT csv);
COPY parameters.first_launch FROM 'C:\csv\FirstLaunchParameters.csv' WITH (FORMAT csv);
COPY parameters.in_game_purchase FROM 'C:\csv\InGamePurchaseParameters.csv' WITH (FORMAT csv);
COPY parameters.stage_end FROM 'C:\csv\StageEndParameters.csv' WITH (FORMAT csv);
COPY parameters.stage_start FROM 'C:\csv\StageStartParameters.csv' WITH (FORMAT csv);
COPY events.currency_purchase FROM 'C:\csv\CurrencyPurchaseEvents.csv' WITH (FORMAT csv);
COPY events.first_launch FROM 'C:\csv\FirstLaunchEvents.csv' WITH (FORMAT csv);
COPY events.game_launch FROM 'C:\csv\GameLaunchEvents.csv' WITH (FORMAT csv);
COPY events.in_game_purchase FROM 'C:\csv\InGamePurchaseEvents.csv' WITH (FORMAT csv);
COPY events.stage_end FROM 'C:\csv\StageEndEvents.csv' WITH (FORMAT csv);
COPY events.stage_start FROM 'C:\csv\StageStartEvents.csv' WITH (FORMAT csv);
